branch-defaults:
  default:
    environment: Origo-env
    group_suffix: null
  master:
    environment: Origo-Scrape-2-env
    group_suffix: null
global:
  application_name: Origo
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
